# Generated by Django 5.0 on 2024-03-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_downloadrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadRequests',
        ),
    ]
